# Generated by Django 3.2.5 on 2022-07-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0015_rename_event_fallevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('vid', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fallevent',
            name='eid',
        ),
    ]
