# Generated by Django 3.2.5 on 2022-07-06 15:14

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0016_auto_20220705_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoevent',
            name='img',
            field=models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='emos'),
        ),
        migrations.AddField(
            model_name='fallevent',
            name='img',
            field=models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='falls'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='img',
            field=models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='actions'),
        ),
    ]
