# Generated by Django 3.2.5 on 2022-07-07 09:24

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0017_auto_20220706_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('personType', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('personId', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('detail', models.CharField(max_length=200)),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='attacks')),
            ],
        ),
        migrations.CreateModel(
            name='Older',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('idcard', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=10)),
                ('r1name', models.CharField(max_length=20)),
                ('r1phone', models.CharField(max_length=30)),
                ('r2name', models.CharField(max_length=20)),
                ('r2phone', models.CharField(max_length=30)),
                ('health', models.CharField(max_length=200)),
                ('regdate', models.TimeField()),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='attacks')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('idcard', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('regdate', models.TimeField()),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='attacks')),
            ],
        ),
        migrations.CreateModel(
            name='UnkownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='unkowns')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('idcard', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('regdate', models.TimeField()),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='attacks')),
            ],
        ),
    ]
