# Generated by Django 3.2.5 on 2022-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0018_attackevent_older_stuff_unkownevent_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoevent',
            name='emo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
