# Generated by Django 3.2.5 on 2022-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0020_auto_20220707_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='older',
            name='regdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='regdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='regdate',
            field=models.DateField(),
        ),
    ]
