# Generated by Django 3.2.5 on 2022-07-14 10:01

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0022_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hasmask', models.CharField(max_length=5)),
                ('detail', models.CharField(max_length=200)),
                ('img', models.ImageField(default='', storage=system.storage.ImageStorage(), upload_to='masks')),
            ],
        ),
    ]
